version: '3'
services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - '9009:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db-api
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco-teste
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

